#' Relative fitness
#'
#' Calculate relative fitness in the population under directional selection.
#'
#' `relative_fitness` takes phenotype values from a population generated by
#' `initialise_population` and calculates absolute fitness as a logistic
#' function of the product of the phenotype values and the selection gradient.
#'
#' Relative fitness is absolute fitness divided by mean absolute fitness.
#'
#' If individuals have NA phenotype the fitness is returned as zero.
#'
#' @param pop A list describing genotypes and positions in a population.
#' Output of `initialise_population`,
#' @param selection_gradient Linear selection gradient.
#'
#' @returns A vector of relative fitness values. If `selection_gradient=0`,
#' returns 1.
relative_fitness <- function(pop, selection_gradient){
  if( selection_gradient == 0) {
    w <- 1
  } else{
    w <- pop$phenotype * selection_gradient
    w <- 1 / (1+exp(-w))
    w <- w / mean(w, na.rm = TRUE)
    w[is.na(w)] <- 0
  }

  w
}
